### PR TITLE
feat: adding support to pt-br language

### PR DESCRIPTION
**Pull request by lacerdev**
Adding translation to brazilian portuguese (pt-br) language.
Please, let me know if I missed something.

### CODE REVIEW

**Comment by MrWook** [comment]
Looks good to me, but just two question.
1. The lastname list seems to be a bit small don't you have a bigger one?
2. I'm just curious here but the last entry of the wikipedia page is `jagdgeschwader`. I don't suspect that you know it but why is this german word so often used on wikipedia in this language? xD

**Comment by lacerdev** [comment]
@MrWook, there are two great questions. hahaha
 1. About lastnames, I couldn't find out a bigger list in official government service. Today I'm fetching surnames in [Wikitionary](https://pt.wiktionary.org/wiki/Ap%C3%AAndice:Sobrenomes_em_portugu%C3%AAs), but in the future the source of surnames must be changed to IBGE official data. IBGE census did not turn available API to get surnames, but only firstnames. It will should be available in the next Census (2022), accord to them.
 2. About this question, you made me a bit curious too. I don't know the answer, but maybe it was influenced by considerable german immigration that Brazil received in history. In some cities, mainly in countryside the population speaks german aside portuguese, and there are a lot of terms originated of german speaked around

I created a project https://github.com/lacerdev/zxcvbn-ts-language-pt-br to maintain and update this translation and I will keep seeking another last names source to update it soon as possible.

**Comment by MrWook** [comment]
1. Alright, but you don't need to create an own repository for it, we already have some parsers in data-scripts which are fetching and parsing dictionaries from remote urls. You can just add a generalized ApiGenerator for your IBGE data and a WikipediaListGenerator for the current lastnames. This is all described in https://zxcvbn-ts.github.io/zxcvbn/guide/languages/#add-a-new-language-package
2. Interessting didn't know about this 👍

**Comment by lacerdev** [comment]
@MrWook , you're right. I didn't realize that 🤦🏼‍♂️ 

I will being to work on it...

**Comment by lacerdev** [comment]
@MrWook , new generators were added for IBGE and Wikitionary data.

Please, take a look.

**Comment by MrWook** [comment]
@lacerdev i just published it. https://www.npmjs.com/package/@zxcvbn-ts/language-pt-br

**Comment by lacerdev** [comment]
@MrWook , thanks for letting me know!

**Pull request merged**
