### PR TITLE
Add separator matcher

### LINKED ISSUE #12: Separators screw with scoring
Separators like whitespaces will greatly increase the scoring: https://github.com/dropbox/zxcvbn/issues/216

image

Maybe we could extract the separators like the java version https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/java/me/gosimple/nbvcxz/matching/SeparatorMatcher.java

### PR DESCRIPTION
**Pull request by domosapien**
Fixes #12 

Adds `separator` matching. Limits separators to common ones (`[ ,._-]`). Could be expanded to any non-ascii / digit.

To get this to work, I had to override `bruteforce` and `repeat` matchers. They would both eat separators and cause the separator to be integrated into other matching. The example used in the issue (`buy by beer`) still uses the `repeat` pattern even when there is a separator matcher unless this is changed. Other examples like `correct horse battery staple` would use `bruteforce` instead of separators. The final result is to remove `bruteforce` matches if they have a separator in them. `repeats` now only match non-separator chars, so they are excluded by default from generating matches with them.

The scoring still feels off to me. I removed additional guesses from being added to repeat separators, as I figured they were enough of a pattern to be easily guessable. This is probably not the right response, and the score still feels high to me. In the issue, the same `buy by beer` has a `nbvcxz` result posted showing a much lower entropy. I seem to agree with that one more than the one I generate.

Regardless, I figured this may be a starting point for someone else to potentially point out problems or provide solutions.

### CODE REVIEW

**Comment by domosapien** [comment]
The ideas thrown around https://github.com/zxcvbn-ts/zxcvbn/issues/12#issuecomment-777777003 may be the better alternatives to strictly matching a new type of pattern and having that impact the entropy too highly.

**Comment by domosapien** [comment]
Example output

https://user-images.githubusercontent.com/5354614/172940412-3ce19dc0-0318-401a-93be-44012b686ca0.mov

**Comment by domosapien** [comment]
Well shoot, I definitely forgot to work on the unit tests after I made more changes. I keep running into `No element indexed by 31` errors, and don't know how to diagnose them. I definitely messed up the repeat tests. I will try to fix that if I have time today.

**Comment by MrWook** [comment]
Hey, thanks for this pull request 👍 
I think the unit test errors are because you changed the repeat matcher a little bit which results in a different behaviour than before with a different scoring even for cases without a separator.

**Comment by MrWook** [comment]
@domosapien could you please resolve the conflicts, so that i can review it once more and maybe merge it this time?

**Comment by domosapien** [comment]
The merge wasn't bad, but there were some failing unit tests for missing translations, which I had just put in as placeholders anyway. I've removed those translations / placeholders to allow for successful unit tests. If you would like to add them, please feel free. I'm not sure what the suggestion would be for separator usage anyway 🙃

**Comment by domosapien** [comment]
I didn't like the scoring that was coming out of the demo. Still seems way too high. I don't know if this should be merged yet.

**Comment by domosapien** [comment]
I actually don't know if the separators are the issue, or the general issue of determining the lowest entropy path and score.

**Comment by MrWook** [comment]
Could you fix the linting, too?

As you can see in your video above this separator matcher that you implement works just fine. It is splitting `buy by beer` correctly and the example from https://github.com/zxcvbn-ts/zxcvbn/issues/143 too. 

The scoring from the java port is a different matter, as the author described. He implemented another matching algorithm as the original doesn't seem quite right. This would be another separated issue for this library but your separater matcher is working as indented :)

**Pull request merged**
