### PR TITLE
Dutch and Belgium

### PR DESCRIPTION
**Pull request by SimonBackx**
I've added two packages for Dutch (common) + Dutch/Belgium (since first and lastnames are different in the Netherlands and Belgium)

What do you think of the changes, and do I need to make any changes before this will get accepted?

### CODE REVIEW

**Comment by SimonBackx** [comment]
Could you clarify the meaning of "straightRow" in the translations? Couldn't find a proper translation since I don't understand it :)

**Comment by MrWook** [comment]
Hey, thanks for the PR.
It's not completely correct but we can get there ^^ I think i should write a "How to add a new language package" :D
The json files inside the language packages are auto-generated with the npm script `generate:languageData`.

Inside `./data-scripts/generate.ts` is an object with with languages and how to get the a language package.
For example 
```
const lists = {
  en: {
    commonWords: {
      source:
        'https://github.com/hermitdave/FrequencyWords/raw/master/content/2018/en/en_50k.txt',
      options: { hasOccurrences: true },
    },
  },
}
```

This will download the list from the source. Inside the source are occurrences values of the common words. Those will be filtered and parsed to the json format of a language packages.
Most of the time you have some sort of list kike this github list from the example with words and a line break. In this case you can just use this default generator.
If your lists are a bit special and need some custom parsing you would need to write a customer generator to retrieve the necessary data from your source.
For example the password list is a custom generator because the file is so big and has another layout.

This means you would need to extend the object with your language and probably use the default generator and set some sources for the packages. After that you can execute the npm script.
The reason for this is that this project should not be a collection of lists for names and so on. We only will be using those lists. This way we can update or exchange lists easily.
Inside the language package you need to add the default stuff for an npm package and the translation file.


I will make an issue to improve the creation of new language packages and for the documentation of it.
For your second question about `straightRow`. It's about the keyboard layout. For example `qwerty` is a straight row on a keyboard.
I guess we should change the translation to something like `Straight rows of keys like "qwerty" are easy to guess.`

**Comment by SimonBackx** [comment]
Okay, I'll try to add a Excel collector to gather the data from the statbel files. Be cautious with the `Straight rows of keys like "qwerty" are easy to guess.`, since that will make some things more complex. In Belgium we user AZERTY, while in the Netherlands QWERTY is used.

**Comment by MrWook** [comment]
Hey, i made a PR for the guide https://github.com/zxcvbn-ts/zxcvbn/pull/21

Back to the `straightRows`:
Your right there are different keyboard layouts so something like this would be more appropriate:
`Straight rows of keys on your keyboard are easy to guess.`

**Comment by SimonBackx** [comment]
@MrWook I've added the ExcelGenerator and removed the common Dutch package for now (if someone wants to search the first and last names from the Netherlands, they could create a separate package). I also added a generator function to only generate for a specific language (this solves the issue that the known passwords file is not available anymore + is a couple of MB to download first). So you don't need to generate all languages if you only make changes in one of them.

I made a small change in the runtime, that correctly writes the eslint errors for index.ts (needed this for debugging, and can imagine that we need readable errors on that place).

**Comment by MrWook** [comment]
Hey, i love the changes nice work!

**Pull request merged**
